language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
os:
  - linux
  - osx
before_deploy:
  - mv target/release/bashdoc "target/release/bashdoc-$TRAVIS_TAG-$TRAVIS_OS_NAME"
  - git config --local user.name "dustinknopoff"
  - git config --local user.email "dustinknopoff@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file:
      - target/release/bashdoc-*
    api_key: $GITHUB_OAUTH_TOKEN