[package]
name = "bashdoc"
version = "0.2.0"
edition = "2018"

[dependencies]
colored = "1.6"
dirs = "1.0.4"
clap = {version = "2.32", features = ["yaml"]}
glob = "0.2"
rayon = "1.0.3"
serde_derive = "1.0.80"
serde = "1.0.80"
serde_json = "1.0.33"
toml = "0.4.8"
nom = "4.1.1"
handlebars = "1.1.0"
notify = "4.0.6"
nom_locate = "0.3.1"