[package]
name = "bashdoc"
version = "0.1.0"
authors = ["Dustin Knopoff <dustinknopoff@gmail.com>"]

[dependencies]
colored = "1.6"
dirs = "1.0.4"
clap = {version = "2.32", features = ["yaml"]}
glob = "0.2"
rayon = "1.0.2"